version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins     # version 2.235.2
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
  
  postgresDB:
    image: postgres
    volumes:
      - database-project-data:/var/lib/postgres/data
    ports: 
      - 5432:5432
    environment:     
      POSTGRES_PASSWORD: <your-password>
      POSTGRES_USER: your-user
      POSTGRES_DB: your-database           
    networks:
      - db-network
  
  pgadmin:
    image: dpage/pgadmin4:4.18
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@domain.de
      PGADMIN_DEFAULT_PASSWORD: <your-password>
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgresDB:pgsql-server"    
    networks:
      - db-network


networks:
  db-network:
  driver: bridge
      

volumes:
  jenkins-home:
  database-project-data:
  pgadmin-data:    


# Postgres Dashboard https://hub.docker.com/r/dpage/pgadmin4/
# For help with jenkins (check Version by Download) https://medium.com/@jimkang/how-to-start-a-new-jenkins-container-and-update-jenkins-with-docker-cf628aa495e9       