version: '3.4'
services:
 teamcity:
    image: jetbrains/teamcity-server
    links:
      - database-teamcity
    ports:
      - 8111:8111
    volumes:
        - teamcity_data:/data/teamcity_server/datadir
        - teamcity_logs:/opt/teamcity/logs
 teamcity-agent:
    image: jetbrains/teamcity-agent
    environment: 
     SERVER_URL: "localhost:8111"
    volumes:
        - teamcity_agent_data:/data/teamcity_agent/conf
 upsource:
    image: jetbrains/upsource:2020.1.1782
    ports:
        - 8110:8080
    volumes:
        - upsource_data:/opt/upsource/data
        - upsource_conf:/opt/upsource/conf
        - upsource_logs:/opt/upsource/logs
        - upsource_backups:/opt/upsource/backups
 hub:
    image: jetbrains/hub:2020.1.12375
    ports:
        - 8112:8080
    volumes:
        - hub_data:/opt/hub/data
        - hub_conf:/opt/hub/conf
        - hub_logs:/opt/hub/logs
        - hub_backups:/opt/hub/backups
 database-teamcity:
    image: postgres
    volumes:
      - database-teamcity-data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: <your-password>
      POSTGRES_USER: teamcity
      POSTGRES_DB: teamcity

volumes:
 teamcity_data:
 teamcity_logs:
 upsource_data:
 upsource_conf:
 upsource_logs:
 upsource_backups:
 hub_backups:
 hub_conf:
 hub_data:
 hub_logs:
 database-teamcity-data:
 teamcity_agent_data:
