version: '3.4'

services:
  traefik:
    image: traefik:v2.0 
    ports: 
      - 8080:8080
      - 80:80
    volumes: 
    - traefik:/var/run/docker.sock
  
  nginx:
     image: nginx  
     ports: 
     - 8080:80
     volumes: 
     - nginx:/usr/share/nginx/html:ro

  wordpress:
    image: wordpress
    ports:
    - 8079:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    
    
#    environment:
#    -e WORDPRESS_DB_HOST=...
# -e WORDPRESS_DB_USER=...
# -e WORDPRESS_DB_PASSWORD=...
# -e WORDPRESS_DB_NAME=...
# -e WORDPRESS_TABLE_PREFIX=...
# -e WORDPRESS_AUTH_KEY=..., -e WORDPRESS_SECURE_AUTH_KEY=..., -e WORDPRESS_LOGGED_IN_KEY=..., -e WORDPRESS_NONCE_KEY=..., -e WORDPRESS_AUTH_SALT=..., -e WORDPRESS_SECURE_AUTH_SALT=..., -e WORDPRESS_LOGGED_IN_SALT=..., -e WORDPRESS_NONCE_SALT=... (default to unique random SHA1s, but only if other environment variable configuration is provided)
# -e WORDPRESS_DEBUG=1 (defaults to disabled, non-empty value will enable WP_DEBUG in wp-config.php)
# -e WORDPRESS_CONFIG_EXTRA=   
# volumes: 

volumes: 
  nginx:
  traefik:
  wordpress:
  db: