version: '3.4'
services:
 jenkins:
    image: jenkins/jenkins     # version 2.235.2
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
 sonarqube:
    image: sonarqube
    volumes:
      - sonarqube-data:/var/sonarqube/data
      - sonarqube-logs:/var/sonarqube/logs
      - sonarqube-conf:/var/sonarqube/conf
      - sonarqube-extensions:/var/sonarqube/extensions
    ports:
      - 9000:9000  
    environment:
      sonar.jdbc.username: sonar 
      sonar.jdbc.password: <your_password>
 nexus3:      
    image: sonatype/nexus3
    volumes: 
      - nexus-data:/nexus-data
    ports: 
      - 8081:8081
    environment: 
      - INSTALL4J_ADD_VM_PARAMS="-Xms2g -Xmx4g -XX:MaxDirectMemorySize=3g  -Djava.util.prefs.userRoot=/some-other-dir"  

volumes:
  jenkins-home:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-conf:
  sonarqube-extensions:
  nexus-data:

  # For help with jenkins https://medium.com/@jimkang/how-to-start-a-new-jenkins-container-and-update-jenkins-with-docker-cf628aa495e9