version: '3.4'
services:
  jira:
    image: atlassian/jira-software
    restart: always
    links:
      - database-jira
    volumes:
      - jira-data:/var/atlassian/jira
    ports:
      - 8190:8080

  confluence:
    image: atlassian/confluence-server
    restart: always
    links:
      - database-confluence
    volumes:
      - confluence-data:/var/atlassian/confluence
    ports:
      - 8090:8090
      - 8091:8091    

  bitbucket:
    image: atlassian/bitbucket-server
    restart: always
    links: 
      - database-bitbucket
    volumes: 
      - bitbucket-data:/var/atlassian/bitbucket
    ports: 
      - 7990:7990
      - 7999:7999

  database-jira:
    image: postgres
    restart: always
    volumes:
      - database-jira-data:/var/lib/postgres/data
    ports: 
      - 5432:5432
    environment:     
      POSTGRES_PASSWORD: 
      POSTGRES_USER: jira
      POSTGRES_DB: jira
    
  database-confluence:
    image: postgres
    restart: always
    volumes:
      - database-confluence-data:/var/lib/postgres/data
    ports: 
      - 5433:5432
    environment:     
      POSTGRES_PASSWORD: 
      POSTGRES_USER: confluence
      POSTGRES_DB: confluence

  database-bitbucket:
    image: postgres
    restart: always
    volumes:
      - database-bitbucket-data:/var/lib/postgres/data
    ports: 
      - 5431:5432
    environment:     
      POSTGRES_PASSWORD: 
      POSTGRES_DB: bitbucket  
      POSTGRES_USER: bitbucket

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:  
  database-jira-data:
  database-confluence-data:
  database-bitbucket-data:   
