version: '3.4'
services:
  jira:
    image: atlassian/jira-software
    links:
      - database-jira
    volumes:
      - jira-data:/var/atlassian/jira
    ports:
      - 8190:8080

  confluence:
    image: atlassian/confluence-server  
    links:
      - database-confluence
    volumes:
      - confluence-data:/var/atlassian/confluence
    ports:
      - 8090:8090
      - 8091:8091    

  bitbucket:
    image: atlassian/bitbucket-server    
    links: 
      - database-bitbucket
    volumes: 
      - bitbucket-data:/var/atlassian/bitbucket
    ports: 
      - 7990:7990
      - 7999:7999

  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity-server-data:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  teamcity-agent:
    image: jetbrains/teamcity-agent
    volumes: 
      - teamcity-agent-conf:/data/teamcity_agent/conf
    environment:
      SERVER_URL: http://localhost:8111

  database-jira:
    image: postgres
    volumes:
      - database-jira-data:/var/lib/postgres/data
    ports: 
      - 5432:5432
    environment:     
      POSTGRES_PASSWORD: <your-password>
      POSTGRES_USER: jira
      POSTGRES_DB: jira
    
  database-confluence:
    image: postgres
    volumes:
      - database-confluence-data:/var/lib/postgres/data
    ports: 
      - 5433:5432
    environment:     
      POSTGRES_PASSWORD: <your-password>
      POSTGRES_USER: confluence
      POSTGRES_DB: confluence

  database-bitbucket:
    image: postgres
    volumes:
      - database-bitbucket-data:/var/lib/postgres/data
    ports: 
      - 5431:5432
    environment:     
      POSTGRES_PASSWORD: <your-password>
      POSTGRES_DB: bitbucket  
      POSTGRES_USER: bitbucket

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:  
  database-jira-data:
  database-confluence-data:
  database-bitbucket-data:   
  teamcity-server-data:
  teamcity-server-logs:
  teamcity-agent-conf:  
